### ISSUE TITLE
writable stream never settles

### ISSUE THREAD

**Issue by FND** [IntrinsicLabs/osgood#15] opened 2019-07-20 13:23 UTC
(I am aware that Osgood is still a young project. It's a welcome effort, so thank you for sharing it.)

I'm struggling to implement streaming responses, e.g. transforming content while proxying a service without artificially prolonging time to first byte.

Since both [`WritableStream`](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream) and [`TransformStream`](https://developer.mozilla.org/en-US/docs/Web/API/TransformStream) appear to be implemented, I cobbled together a minimal example loosely based on a related [Service Worker sample](https://gist.github.com/domenic/ea5ebedffcee27f552e103963cf8585c):

```javascript
// `examples/simple/hello.js`
export default async (request, context) => {
    let transform = new TransformStream();

    let stream = transform.writable;
    let writer = stream.getWriter();
    writer.write("Hello World"); // see update below
    writer.close();

    return new Response(transform.readable, {
        status: 404,
        headers: new Headers({
            "Content-Type": "text/plain"
        })
    });
};
```

However, that results in no body content being sent over the wire; the request never completes after sending response headers (which include `Transfer-Encoding: chunked`).

As far as I can tell, none of the promises - `write.ready` as well as `#write`'s and `#close`'s return values - ever settle. It's quite possible that this is an issue with my example, perhaps based on wrong assumptions?

----

Update: It's possible I misunderstood `WritableStream`, as `writer.write(new Uint8Array([1, …]))` does result in the request completing - though with an empty body; `await`ing `writer.ready` never settles here either. I've also tried [using `TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream#Examples), but that resulted in "Failed to encode: the 'stream' option is unsupported".

**Comment by bengl** [comment] 2019-07-23 06:51
Hi @FND! Thanks for reporting this! It seems to have been caused by a missing early-return, which I've fixed in #18. I've tested it with your example code and derived a test case from your example. Still, if you're able, it would be great if you could also test it as well.

**Comment by FND** [comment] 2019-07-23 07:01
Thanks for the quick response! I'd be happy to test it, but I'm currently not set up for compiling Rust - is there a prebuilt binary I could use (macOS or Linux¹); perhaps one's being generated by Travis CI anyway?

**Closed** 2019-07-23 19:40 UTC
Labels: bug

**Comment by FND** [comment] 2019-08-09 10:25
I've just gotten around to testing this with v0.2.1 and it seems to work just fine now - no need for `Uint8Array` or `TextEncoder` either, apparently; writing plain strings onto the stream just works.

Thank you!
